name: NIP Dependency Tree
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GraphViz
        run: sudo apt-get update && sudo apt-get install graphviz

      - name: Build dependency tree
        run: |
          # Parse NIPs and generate .dot file
          python parse_nips.py

          # Generate dependency tree image
          dot -Tpng -o tree.png tree.dot

      - name: Upload tree image
        uses: actions/upload-artifact@v2
        with:
          name: dependency-tree
          path: tree.png

