name: NIP Dependency Tree
on:
  push:
    branches:
      - dependency-tree

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          myToken: ${{ secrets.GITHUB_TOKEN  }}

      - name: Install GraphViz
        run: sudo apt-get update && sudo apt-get install graphviz

      - name: Build dependency tree
        run: |
          # Parse NIPs and generate .dot file
          python parse_nips.py

          # Generate dependency tree image
          dot -Tpng -o tree1.png tree1.dot

      - name: Upload tree image
        uses: actions/upload-artifact@v3
        with:
          name: dependency-tree
          path: tree1.png
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: 'Your commit message'
          add: 'tree1.png'

